### ISSUE TITLE
NoSQL Backup work item bad setting default

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1023]
The default value added on line 50 of MangoNoSqlSystemSettingsDefinition is bad. It's an integer 0 but is treated different ways in different place. Being an integer causes a stack trace like the following:

ERROR 2017-05-30T10:59:31,343 (com.infiniteautomation.nosql.maint.MangoNoSqlBackupWorkItem$NoSqlBackupTask.run:301) - Unparseable date: "0"
java.text.ParseException: Unparseable date: "0"
        at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_121]
        at com.infiniteautomation.nosql.maint.MangoNoSqlBackupWorkItem$NoSqlBackupTask.run(MangoNoSqlBackupWorkItem.java:287) [mangoNoSqlDatabase-3.1.0-SNAPSHOT.jar:?]
        at com.serotonin.timer.Task.runTask(Task.java:179) [mango-3.1.0-SNAPSHOT.jar:?]
        at com.serotonin.timer.TaskWrapper.run(TaskWrapper.java:23) [mango-3.1.0-SNAPSHOT.jar:?]
        at com.serotonin.timer.OrderedThreadPoolExecutor$OrderedTaskCollection.run(OrderedThreadPoolExecutor.java:307) [mango-3.1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

There are other places still, like the DWR, which wants it to be an integer value. Because it gets a string if a backup ever succeeded, the default value (0) is given to the SystemSettings page when loaded, but this date is not displayed anywhere.

**Comment by Puckfist** [comment]
This was fixed a while ago by returning a default value of null.
