### ISSUE TITLE
SystemEventTypeSettingsListenerDefinition NPE

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1024]
```
ERROR 2017-05-30T15:12:40,061 (com.serotonin.m2m2.rt.maint.BackgroundProcessing$RejectableWorkItemRunnable.run:559) - Error in work item 
java.lang.NullPointerException: null
	at com.serotonin.m2m2.rt.event.type.SystemEventTypeSettingsListenerDefinition.SystemSettingsSaved(SystemEventTypeSettingsListenerDefinition.java:26) ~[classes/:?]
	at com.serotonin.m2m2.vo.systemSettings.SystemSettingsEventDispatcher$DispatcherExecution.execute(SystemSettingsEventDispatcher.java:110) ~[classes/:?]
	at com.serotonin.m2m2.rt.maint.BackgroundProcessing$RejectableWorkItemRunnable.run(BackgroundProcessing.java:556) [classes/:?]
	at com.serotonin.timer.Task.runTask(Task.java:179) [classes/:?]
	at com.serotonin.timer.TaskWrapper.run(TaskWrapper.java:23) [classes/:?]
	at com.serotonin.timer.OrderedThreadPoolExecutor$OrderedTaskCollection.run(OrderedThreadPoolExecutor.java:307) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by jazdw** [comment]
Works now.
