### ISSUE TITLE
Point hierarchy rest controller - concurrent modification exception

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1087]
Because the cachedPointHierarchy object is shared to callees of DataPointDao's getPointHierarchy, there exists the possibility that it is modified by one of its consumers while being iterated over. Here is the stack trace that brought it to my attention:

ERROR 2017-09-14 12:45:17,418 (com.serotonin.m2m2.web.mvc.rest.v1.exception.RestExceptionHandler.handleExceptionInternal:80) -
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.writeFoldersRecursively(PointHierarchyRestController.java:353)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.writeFoldersRecursively(PointHierarchyRestController.java:373)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.writeFoldersRecursively(PointHierarchyRestController.java:373)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.writeFoldersRecursively(PointHierarchyRestController.java:373)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.writeFoldersRecursively(PointHierarchyRestController.java:373)
        at com.serotonin.m2m2.web.mvc.rest.v1.PointHierarchyRestController$PointHiearchyFolderStream.streamData(PointHierarchyRestController.java:319)
        at com.serotonin.m2m2.web.mvc.rest.v1.mapping.JsonStreamSerializer.serialize(JsonStreamSerializer.java:27)
        at com.serotonin.m2m2.web.mvc.rest.v1.mapping.JsonStreamSerializer.serialize(JsonStreamSerializer.java:19)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:602)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:264)
        at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:100)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:202)
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:186)
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:80)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
.....

**Comment by Puckfist** [comment]
akin to #1095 probably

**Comment by Puckfist** [comment]
Because the hierarchy is either read only or a copy, I will close this issue as fixed.
