### ISSUE TITLE
Upgrade 18 silently fails on new H2 database.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1135]
When starting mango with a fresh database the schema version is set to 18 when it should be set to 20.  Nothing was noticed in the logs.

Restarting mango attempts to run Upgrade 18 again and fails with this message:

`Caused by: org.h2.jdbc.JdbcSQLException: Table "EVENTHANDLERSMAPPING" already exists; SQL statement:
CREATE TABLE eventHandlersMapping (eventHandlerId int not null, eventTypeName varchar(32) NOT NULL, eventSubtypeName varchar(32) NOT NULL DEFAULT '', eventTypeRef1 int NOT NULL, eventTypeRef2 int NOT NULL);  [42101-181]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:111) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.CommandContainer.update(CommandContainer.java:78) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:185) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:159) ~[h2-1.4.181.jar:1.4.181]
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:435) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.serotonin.m2m2.db.H2Proxy.runScript(H2Proxy.java:149) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:129) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:143) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:134) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.Upgrade18.upgrade(Upgrade18.java:28) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:98) ~[classes/:?]
	... 5 more`

**Comment by terrypacker** [comment]
Fixed.
