### ISSUE TITLE
Persistent Sync - Array index out of bounds escaping to stderr

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1189]
Exception in thread "high-pool-2-thread-49" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.serotonin.m2m2.persistent.pub.SyncHandler$PointSync.run(SyncHandler.java:257)
	at com.serotonin.timer.sync.Synchronizer$TaskWrapper.run(Synchronizer.java:150)
	at com.serotonin.timer.Task.runTask(Task.java:179)
	at com.serotonin.timer.TaskWrapper.run(TaskWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I think the more sync threads you have, the easier this is to cause. Also, run the syncs very frequently.

**Comment by terrypacker** [comment]
I would fix this 2 ways.  1 by wrapping everything in the PointSync.run method in a try/catch and 2 by changing the list of points ```pointsToSync``` into a ConcurrentLinkedQueue or adding synchronization to that list.

**Comment by terrypacker** [comment]
Released 3.3.1
