### ISSUE TITLE
Swagger - doesn't load on IPv6

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1215]
Attempting to load swagger over IPv6 I see these messages in my browser's developer console:
Most important, probably:
'XMLHttpRequest': Invalid URL
    at new module.exports (http://[fe80::1234]/swagger/lib/shred.bundle.js:2559:9)

all ouput:
["added key 4782b0f9-token-ed9c701fbde6"]
http://[fe80::1234]/swagger/swagger-ui.js:70 ["base is http://[fe80::1234]/swagger/"]
http://[fe80::1234]/swagger/lib/shred.bundle.js:1726 no zlib library
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:1726
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
require_ @ http://[fe80::1234]/swagger/lib/shred.bundle.js:143
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:778
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
require_ @ http://[fe80::1234]/swagger/lib/shred.bundle.js:143
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:370
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
ShredHttpClient @ http://[fe80::1234]/swagger/lib/swagger.js:1368
SwaggerHttp.execute @ http://[fe80::1234]/swagger/lib/swagger.js:1253
SwaggerApi.build @ http://[fe80::1234]/swagger/lib/swagger.js:151
SwaggerApi @ http://[fe80::1234]/swagger/lib/swagger.js:113
SwaggerUi.load @ http://[fe80::1234]/swagger/swagger-ui.js:1281
(anonymous) @ http://[fe80::1234]/swagger/:72
k @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
fireWith @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
ready @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
D @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
http://[fe80::1234]/swagger/lib/shred.bundle.js:1734 no iconv library
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:1734
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
require_ @ http://[fe80::1234]/swagger/lib/shred.bundle.js:143
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:778
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
require_ @ http://[fe80::1234]/swagger/lib/shred.bundle.js:143
(anonymous) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:370
require.modules.(anonymous function) @ http://[fe80::1234]/swagger/lib/shred.bundle.js:154
require @ http://[fe80::1234]/swagger/lib/shred.bundle.js:7
ShredHttpClient @ http://[fe80::1234]/swagger/lib/swagger.js:1368
SwaggerHttp.execute @ http://[fe80::1234]/swagger/lib/swagger.js:1253
SwaggerApi.build @ http://[fe80::1234]/swagger/lib/swagger.js:151
SwaggerApi @ http://[fe80::1234]/swagger/lib/swagger.js:113
SwaggerUi.load @ http://[fe80::1234]/swagger/swagger-ui.js:1281
(anonymous) @ http://[fe80::1234]/swagger/:72
k @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
fireWith @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
ready @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
D @ http://[fe80::1234]/swagger/lib/jquery-1.8.0.min.js:2
http://[fe80::1234]/swagger/lib/shred.bundle.js:2559 Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at new module.exports (http://[fe80::1234]/swagger/lib/shred.bundle.js:2559:9)
    at Object.http.request (http://[fe80::1234]/swagger/lib/shred.bundle.js:2442:15)
    at createRequest (http://[fe80::1234]/swagger/lib/shred.bundle.js:1165:23)
    at new Request (http://[fe80::1234]/swagger/lib/shred.bundle.js:847:3)
    at Shred.request (http://[fe80::1234]/swagger/lib/shred.bundle.js:388:12)
    at ShredHttpClient.execute (http://[fe80::1234]/swagger/lib/swagger.js:1451:21)
    at SwaggerHttp.execute (http://[fe80::1234]/swagger/lib/swagger.js:1253:34)
    at SwaggerApi.build (http://[fe80::1234]/swagger/lib/swagger.js:151:21)
    at new SwaggerApi (http://[fe80::1234]/swagger/lib/swagger.js:113:10)
    at SwaggerUi.load (http://[fe80::1234]/swagger/swagger-ui.js:1281:18)

**Comment by Puckfist** [comment]
Maybe fixed by #1260
