### ISSUE TITLE
AnalogChangeDetectorRT - NPE When Handling Email Event

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1256]
```
ERROR 2018-04-17T13:59:49,853 (com.serotonin.m2m2.rt.event.handlers.EmailHandlerRT.sendEmail:425) -  
java.lang.NullPointerException: null
	at com.serotonin.m2m2.rt.event.handlers.EmailHandlerRT.sendEmail(EmailHandlerRT.java:268) [classes/:?]
	at com.serotonin.m2m2.rt.event.handlers.EmailHandlerRT.sendEmail(EmailHandlerRT.java:190) [classes/:?]
	at com.serotonin.m2m2.rt.event.handlers.EmailHandlerRT.eventRaised(EmailHandlerRT.java:129) [classes/:?]
	at com.serotonin.m2m2.rt.EventManagerImpl.handleRaiseEvent(EventManagerImpl.java:948) [classes/:?]
	at com.serotonin.m2m2.rt.EventManagerImpl.raiseEvent(EventManagerImpl.java:217) [classes/:?]
	at com.serotonin.m2m2.rt.event.detectors.PointEventDetectorRT.raiseEvent(PointEventDetectorRT.java:44) [classes/:?]
	at com.serotonin.m2m2.rt.event.detectors.AnalogChangeDetectorRT.handleValue(AnalogChangeDetectorRT.java:211) [classes/:?]
	at com.serotonin.m2m2.rt.event.detectors.AnalogChangeDetectorRT.pointLogged(AnalogChangeDetectorRT.java:234) [classes/:?]
	at com.serotonin.m2m2.rt.dataImage.DataPointRT$EventNotifyWorkItem.execute(DataPointRT.java:746) [classes/:?]
	at com.serotonin.m2m2.rt.maint.BackgroundProcessingImpl$RejectableWorkItemRunnable.run(BackgroundProcessingImpl.java:632) [classes/:?]
	at com.serotonin.timer.Task.runTask(Task.java:179) [classes/:?]
	at com.serotonin.timer.TaskWrapper.run(TaskWrapper.java:23) [classes/:?]
	at com.serotonin.timer.OrderedThreadPoolExecutor$OrderedTaskCollection.run(OrderedThreadPoolExecutor.java:336) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

From a quick review of the code I believe we should modify the calls to raiseEvent(..) on lines 211,226,240 to call createContext() instead of passing in null.

**Comment by Puckfist** [comment]
Good catch
