### ISSUE TITLE
DoubleConverter fails with Infinite or NaN

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1286]
If you create a numeric point with a range rendered that uses "Infinity" or "-Infinity" as a range value, it will accept it and be valid but you will no longer be able to export that point as JSON through the new UI due to an exception akin to, 

java.lang.NumberFormatException: Infinite or NaN
        at java.math.BigDecimal.<init>(BigDecimal.java:895) ~[?:1.8.0_162]
        at java.math.BigDecimal.<init>(BigDecimal.java:872) ~[?:1.8.0_162]
        at com.serotonin.json.convert.DoubleConverter.jsonWrite(DoubleConverter.java:22) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.ObjectTypeWriter.writeEntry(ObjectTypeWriter.java:35) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:119) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:49) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.CollectionConverter.jsonWrite(CollectionConverter.java:29) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.ObjectTypeWriter.writeEntry(ObjectTypeWriter.java:35) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:119) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:49) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.ObjectTypeWriter.writeEntry(ObjectTypeWriter.java:35) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:119) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:49) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.CollectionConverter.jsonWrite(CollectionConverter.java:29) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.convert.MapConverter.jsonWrite(MapConverter.java:27) ~[mango-3.4.4.jar:?]
        at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:39) ~[mango-3.4.4.jar:?]
        at com.infiniteautomation.mango.rest.v2.JsonEmportV2Controller.export(JsonEmportV2Controller.java:214) ~[mango-api-3.4.3.jar:?]

**Comment by Puckfist** [comment]
Tried to clean up by writing a BigDecimal that is larger / smaller than Double.MAX_VALUE  / MIN_VALUE but ended up getting nulls in my JSON export for these fields in the new UI. This lead me to believe it's some Jackson configuration perhaps, since I was able to see in inspecting the node that my range renderers 'from' was definitely -1.8e309
