### ISSUE TITLE
Modbus startup race condition

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1318]
I believe, given a Mango with a Modbus data source reading a Modbus publisher in the same instance (don't ask me why someone would do that..... it may only be the fault of one or the other), there exists a race condition which if lost produces this exception at stderr on many (but not all) startups

Exception in thread "pool-5-thread-2" java.lang.NullPointerException
	at com.serotonin.modbus4j.sero.messaging.StreamTransport.run(StreamTransport.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by terrypacker** [comment]
I don't 100% follow where the race condition is, can you provide more info?
