### ISSUE TITLE
Send Email No Timeout Setting

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1351]
We should add an env property to timeout the EmailSender.  The default is no timeout.

[https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html](
https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html)

Hung Thread Stacktrace:

```
java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:124)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x6bfa1020> (a java.io.BufferedInputStream)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2182)
	at com.sun.mail.smtp.SMTPTransport.close(SMTPTransport.java:1212)
	- locked <0x6bfa00c0> (a com.sun.mail.smtp.SMTPTransport)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:459)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:362)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350)
	at com.serotonin.web.mail.EmailSender.send(EmailSender.java:199)
	at com.serotonin.web.mail.EmailSender.send(EmailSender.java:190)
	at com.serotonin.web.mail.EmailSender.send(EmailSender.java:143)
	at com.serotonin.m2m2.rt.maint.work.EmailWorkItem.execute(EmailWorkItem.java:89)
	at com.serotonin.m2m2.rt.maint.BackgroundProcessingImpl$WorkItemRunnable.run(BackgroundProcessingImpl.java:676)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by terrypacker** [comment]
Added timeout as system setting.  There is no help for the system settings page in the UI so I couldn't add that.  It's in milliseconds and 0 means no timeout.  Negative numbers are invalid.
