### ISSUE TITLE
Zero-byte module.signed file prevents Mango startup

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1400]
And has its error message escape to stderr:

Exception in thread "main" java.lang.RuntimeException: Module /opt/mango/web/modules/lang_en: name not defined in module properties
	at com.serotonin.m2m2.Main.loadModules(Main.java:402)
	at com.serotonin.m2m2.Main.main(Main.java:119)

**Comment by terrypacker** [comment]
Any idea how that file was 0 bytes?

**Comment by Puckfist** [comment]
No. Especially odd considering this unit in question had been QA'ed and booted several times by Dave before being sent to the customer who discovered this on a MangoES
