### ISSUE TITLE
Permission Joins Cause Duplicate Rows when Dao joins other tables.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1589]
For an example see the data point dao and it's join on the data source table.  For a temporary fix I've set the selects to do a select distinct, see referenced commit.

You have to be non-admin otherwise the permission joins are not used and this doesn't happen.

**Comment by terrypacker** [comment]
This is now causing problems when using the data point query in the watchlists:

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Order by expression "WLP.SORTORDER" must be in the result list in this case; SQL statement:
select distinct DP.ID, DP.XID, DP.NAME, DP.DATA, DP.DATASOURCEID, DP.DEVICENAME, DP.ENABLED, DP.LOGGINGTYPE, DP.INTERVALLOGGINGPERIODTYPE, DP.INTERVALLOGGINGPERIOD, DP.INTERVALLOGGINGTYPE, DP.TOLERANCE, DP.PURGEOVERRIDE, DP.PURGETYPE, DP.PURGEPERIOD, DP.DEFAULTCACHESIZE, DP.DISCARDEXTREMEVALUES, DP.ENGINEERINGUNITS, DP.ROLLUP, DP.DATATYPEID, DP.SETTABLE, DP.JSONDATA, DP.READPERMISSIONID, DP.SETPERMISSIONID, DS.NAME, DS.XID, DS.DATASOURCETYPE from dataPoints DP join dataSources DS on DS.ID = DP.DATASOURCEID join watchListPoints WLP on WLP.DATAPOINTID = DP.ID where WLP.WATCHLISTID = cast(? as int) order by WLP.SORTORDER [90068-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.dml.Query.initExpression(Query.java:607) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.dml.Query.initOrder(Query.java:525) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.dml.Select.init(Select.java:1042) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parseQuery(Parser.java:2627) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parsePrepared(Parser.java:868) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:843) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:815) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.prepareCommand(Parser.java:738) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareLocal(Session.java:657) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareCommand(Session.java:595) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352) ~[h2-1.4.200.jar:1.4.200]
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1556) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
```

**Comment by terrypacker** [comment]
Generate a large DB with many points and confirm that using `DISTINCT` does not affect performance.

**Comment by terrypacker** [comment]
I have just seen this with event queries when crafting the permission joins.  We *MUST* use distinct in the current form of the joins.

**Comment by terrypacker** [comment]
This is likely fixed due to only using a single permission JOIN for read permission.  If we do multiple permission JOINS (not something we do yet) then we will have to re-visit this.

**Comment by terrypacker** [comment]
After removing `SELECT DISTINCT` from all the daos we found that the concept of an owner of a VO was still causing problems as the permission query became painful to craft.  The solution was to remove the concept of an owner from Advanced Scheduler, Excel Reports, Watchlists.
