### ISSUE TITLE
NPE logged when running tests

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1689]
Common.eventManager is a SimpleEventManager which tries to call deactivateEvents but its userDao is null.

```
ERROR 2021-01-12T17:42:48,458 (com.serotonin.m2m2.rt.RuntimeManagerImpl.stopDataSourceShutdown:444) - Data source 'DS_1' failed proper termination. 
java.lang.NullPointerException: null
	at com.serotonin.m2m2.rt.EventManagerImpl.deactivateEvents(EventManagerImpl.java:385) ~[classes/:?]
	at com.serotonin.m2m2.rt.EventManagerImpl.cancelEventsForDataPoints(EventManagerImpl.java:670) ~[classes/:?]
	at com.serotonin.m2m2.rt.RuntimeManagerImpl.stopDataSourceShutdown(RuntimeManagerImpl.java:435) ~[classes/:?]
	at com.serotonin.m2m2.rt.DataSourceGroupTerminator.processItem(DataSourceGroupTerminator.java:48) ~[classes/:?]
	at com.serotonin.m2m2.rt.DataSourceGroupTerminator.processItem(DataSourceGroupTerminator.java:22) ~[classes/:?]
	at com.serotonin.m2m2.rt.GroupProcessor.lambda$submit$0(GroupProcessor.java:65) ~[classes/:?]
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82) ~[spring-security-core-5.4.2.jar:5.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Disconnected from the target VM, address: '127.0.0.1:58979', transport: 'socket'
```

**Comment by terrypacker** [comment]
This happens in `DataPointEventsTest`
