### ISSUE TITLE
Unlicensed 4.0.0 Upgrade Fails to Start

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1704]
```
INFO  2021-03-03T13:25:49,831 (com.infiniteautomation.mango.cloudConnect.client.CloudConnectClient.initialize:216) - Cloud Connect client not licensed 
com.serotonin.m2m2.LicenseViolatedException: Client license failure. Mango core must be licensed.
	at com.infiniteautomation.mango.cloudConnect.license.CloudConnectLicense.clientStarted(CloudConnectLicense.java:78) ~[?:?]
	at com.infiniteautomation.mango.cloudConnect.client.CloudConnectClient.start(CloudConnectClient.java:340) ~[?:?]
	at com.infiniteautomation.mango.cloudConnect.client.CloudConnectClient.initialize(CloudConnectClient.java:214) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:429) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1780) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.3.jar:5.3.3]
	at com.serotonin.m2m2.Lifecycle.springRuntimeContextInitialize(Lifecycle.java:386) ~[ma-priv-4.0.0-beta.8.jar:?]
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:292) ~[ma-priv-4.0.0-beta.8.jar:?]
	at com.serotonin.m2m2.Main.main(Main.java:202) ~[ma-priv-4.0.0-beta.8.jar:?]
```

This makes Mango terminate.

**Comment by terrypacker** [comment]
This may not be due to cloud connect.  Need to test with > 300 data points.

**Comment by terrypacker** [comment]
Tested and Mango will start unlicensed with > 300 data points AND cloud connect enabled.  The effects are:

1. Cloud connect does not start
2. System scheduled to shutdown in 60 minutes
