### ISSUE TITLE
Slow Data Source Shutdown - Large Data Source with Many active Data Point Events

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1707]
On a very large data source with many active events on the points a data source can take a long time to shutdown compared to its startup time.  This was noticed on a SNAPSHOT build from a month or so ago.

The code in the below path has been modified in the latest beta release and may be faster now...

The bulk of the time is spent in this method:
` com.serotonin.m2m2.rt.EventManagerImpl.cancelEventsForDataPoints(EventManagerImpl.java:670)`

jstack output:
```
"Mango shared executor service" #56707 daemon prio=5 os_prio=0 cpu=427943.95ms elapsed=681495.99s tid=0x00007faad800f800 nid=0x327c6d runnable  [0x00007faaa7efc000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.8/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.8/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.8/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.8/SocketInputStream.java:140)
	at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
	at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
	at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
	- locked <0x00007fb89a22cc88> (a com.mysql.cj.protocol.ReadAheadInputStream)
	at java.io.FilterInputStream.read(java.base@11.0.8/FilterInputStream.java:133)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:540)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:710)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:649)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:948)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	- locked <0x00007fb89a21bcc8> (a com.mysql.cj.jdbc.ConnectionImpl)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	- locked <0x00007fb89a21bcc8> (a com.mysql.cj.jdbc.ConnectionImpl)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4192)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:464)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:641)
	at org.jooq.impl.AbstractResultQuery.fetchOneInto(AbstractResultQuery.java:664)
	at org.jooq.impl.SelectImpl.fetchOneInto(SelectImpl.java:3094)
	at com.serotonin.m2m2.db.dao.DataPointDao.getReadPermissionId(DataPointDao.java:1007)
	at com.infiniteautomation.mango.spring.service.PermissionService.hasDataPointReadPermission(PermissionService.java:328)
	at com.serotonin.m2m2.rt.event.type.DataPointEventType.hasPermission(DataPointEventType.java:158)
	at com.infiniteautomation.mango.spring.service.PermissionService.hasEventTypePermission(PermissionService.java:242)
	at com.serotonin.m2m2.rt.EventManagerImpl.deactivateEvents(EventManagerImpl.java:403)
	at com.serotonin.m2m2.rt.EventManagerImpl.cancelEventsForDataPoints(EventManagerImpl.java:670)
	at com.serotonin.m2m2.rt.RuntimeManagerImpl.stopDataSourceShutdown(RuntimeManagerImpl.java:445)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.8/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.8/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.8/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.8/Method.java:566)
	at com.infiniteautomation.mango.spring.components.RunAsImpl.lambda$runAsProxy$0(RunAsImpl.java:89)
	at com.infiniteautomation.mango.spring.components.RunAsImpl$$Lambda$533/0x00007fab20ad9908.invoke(Unknown Source)
	at com.sun.proxy.$Proxy71.stopDataSourceShutdown(Unknown Source)
	at com.serotonin.m2m2.rt.DataSourceGroupTerminator.processItem(DataSourceGroupTerminator.java:48)
	at com.serotonin.m2m2.rt.DataSourceGroupTerminator.processItem(DataSourceGroupTerminator.java:22)
	at com.serotonin.m2m2.rt.GroupProcessor.lambda$submit$0(GroupProcessor.java:66)
	at com.serotonin.m2m2.rt.GroupProcessor$$Lambda$577/0x00007fab208d3d08.run(Unknown Source)
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.8/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.8/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)
```

**Comment by terrypacker** [comment]
This is fixed in 4.0.0 by a more efficient UPDATE query
