### ISSUE TITLE
Cannot export event handler with publisher event type with referenceId1 set to 0

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1731]
If you create any event handler that handles this event type
![image](https://user-images.githubusercontent.com/3579645/118721262-dbecf500-b7e7-11eb-9169-3ac0181286f9.png)

You cannot export it via the configuration import/export tool. An exception is logged
```
ERROR 2021-05-13T16:37:17,274 (com.infiniteautomation.mango.rest.latest.exception.RestExceptionHandler.handleExceptionInternal:250)[RestExceptionHandler] - Server error, returning status 500 INTERNAL_SERVER_ERROR for request uri=/rest/latest/json-emport;client=127.0.0.1;session=node096fqukeagpzz1dgi5om6mvn5e0;user=admin
java.lang.NullPointerException: null
	at com.serotonin.m2m2.rt.event.type.PublisherEventType.jsonWrite(PublisherEventType.java:133) ~[classes/:?]
	at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:66) ~[classes/:?]
	at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:49) ~[classes/:?]
	at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:50) ~[classes/:?]
	at com.serotonin.json.convert.CollectionConverter.jsonWrite(CollectionConverter.java:29) ~[classes/:?]
	at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:50) ~[classes/:?]
	at com.serotonin.json.type.ObjectTypeWriter.writeEntry(ObjectTypeWriter.java:35) ~[classes/:?]
	at com.serotonin.m2m2.vo.event.AbstractEventHandlerVO.jsonWrite(AbstractEventHandlerVO.java:172) ~[classes/:?]
	at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:66) ~[classes/:?]
	at com.serotonin.json.convert.JsonPropertyConverter.jsonWrite(JsonPropertyConverter.java:49) ~[classes/:?]
	at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:50) ~[classes/:?]
	at com.serotonin.json.convert.CollectionConverter.jsonWrite(CollectionConverter.java:29) ~[classes/:?]
	at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:50) ~[classes/:?]
	at com.serotonin.json.convert.MapConverter.jsonWrite(MapConverter.java:27) ~[classes/:?]
	at com.serotonin.json.type.JsonTypeWriter.writeObject(JsonTypeWriter.java:50) ~[classes/:?]
	at com.infiniteautomation.mango.rest.latest.JsonEmportController.export(JsonEmportController.java:210) ~[?:?]
```

A similar problem occurs when selecting the top level data source event type.

**Comment by jazdw** [comment]
Also cannot import an event handler with event type like this -
```
          "XID": "62ee0fc0-ec8d-45ae-9443-2ad0548147d3",
          "sourceType": "DATA_SOURCE",
          "dataSourceEventType": null
```


Event handler 'EH_c86d8416-ec3a-4b0a-99ef-974508b3d2dc': Event type must have a 'dataSourceEventType'. Valid values are [POLL_ABORTED]

**Comment by jazdw** [comment]
The problem stems from the fact that the event types for an event handler support wildcards for the subtype (empty string means match any) and referenceId1, and referenceId2 (0 means match any). However the `EventType` classes assume the values are literal and try to get the publisher for id 0 e.g. see `com.serotonin.m2m2.rt.event.type.PublisherEventType#jsonWrite`
