### ISSUE TITLE
Mango REST API Severe Bug with Statistics Access

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#336]
When adding the value 0 or -1 as the TimePeriod value, Mango goes into an endless loop and can crash.  Any value equal to or less than 0 should return an error response to the client.  Values between 0 and 1 should be tested for validity.

ERROR 2015-02-19 09:13:11,467 (com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.statistics.NumericPointValueStatisticsQuantizerJsonCallback.quantizedStatistics:96) -  
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:337)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:128)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:645)
	at org.eclipse.jetty.util.IteratingCallback.processIterations(IteratingCallback.java:233)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:193)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:455)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:745)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:778)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:131)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:124)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:339)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.deflate(DeflatedOutputStream.java:74)
	at org.eclipse.jetty.servlets.gzip.DeflatedOutputStream.write(DeflatedOutputStream.java:64)
	at org.eclipse.jetty.servlets.gzip.GzipOutputStream.write(GzipOutputStream.java:46)
	at org.eclipse.jetty.servlets.gzip.AbstractCompressedStream.write(AbstractCompressedStream.java:226)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:1853)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeNumber(UTF8JsonGenerator.java:824)
	at com.fasterxml.jackson.core.JsonGenerator.writeNumberField(JsonGenerator.java:1149)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.PointValueTimeJsonWriter.writePointValueTime(PointValueTimeJsonWriter.java:33)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.statistics.NumericPointValueStatisticsQuantizerJsonCallback.quantizedStatistics(NumericPointValueStatisticsQuantizerJsonCallback.java:47)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.statistics.NumericPointValueStatisticsQuantizerJsonCallback.quantizedStatistics(NumericPointValueStatisticsQuantizerJsonCallback.java:23)
	at com.serotonin.m2m2.view.quantize2.AnalogStatisticsQuantizer.closePeriod(AnalogStatisticsQuantizer.java:46)
	at com.serotonin.m2m2.view.quantize2.AbstractDataQuantizer.nextPeriod(AbstractDataQuantizer.java:69)
	at com.serotonin.m2m2.view.quantize2.AbstractDataQuantizer.data(AbstractDataQuantizer.java:51)
	at com.serotonin.m2m2.view.quantize2.AbstractDataQuantizer.data(AbstractDataQuantizer.java:40)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.PointValueRollupCalculator$1.row(PointValueRollupCalculator.java:109)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.PointValueRollupCalculator$1.row(PointValueRollupCalculator.java:106)
	at com.infiniteautomation.nosql.MangoNoSqlPointValueDao$MappedRowPointValueQueryCallback.sample(MangoNoSqlPointValueDao.java:581)
	at com.infiniteautomation.nosql.MangoNoSqlPointValueDao$MappedRowPointValueQueryCallback.sample(MangoNoSqlPointValueDao.java:566)
	at org.tinytsdb.impl.TinyTSDBImpl$CallbackWrapper.sample(TinyTSDBImpl.java:364)
	at org.tinytsdb.impl.Shard.query(Shard.java:154)
	at org.tinytsdb.impl.Series.query(Series.java:146)
	at org.tinytsdb.impl.TinyTSDBImpl.query(TinyTSDBImpl.java:287)
	at org.tinytsdb.impl.TinyTSDBImpl.query(TinyTSDBImpl.java:269)
	at com.infiniteautomation.nosql.MangoNoSqlPointValueDao.getPointValuesBetween(MangoNoSqlPointValueDao.java:221)
	at com.serotonin.m2m2.db.dao.PointValueDaoMetrics.getPointValuesBetween(PointValueDaoMetrics.java:166)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.PointValueRollupCalculator.calculate(PointValueRollupCalculator.java:105)
	at com.serotonin.m2m2.web.mvc.rest.v1.model.pointValue.PointValueRollupCalculator.streamData(PointValueRollupCalculator.java:124)
	at com.serotonin.m2m2.web.mvc.rest.v1.JsonArraySerializer.serialize(JsonArraySerializer.java:31)
	at com.serotonin.m2m2.web.mvc.rest.v1.JsonArraySerializer.serialize(JsonArraySerializer.java:19)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1887)
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.writeInternal(MappingJackson2HttpMessageConverter.java:253)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:143)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:125)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:71)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:122)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
	at com.serotonin.m2m2.web.mvc.rest.v1.CustomHeadersFilter.doFilter(CustomHeadersFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:485)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:524)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)
	... 86 more

**Comment by terrypacker** [comment]
Closing as fixed, tested and doesn't seem to exist anymore.
