### ISSUE TITLE
Better Unit Validation

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#344]
A corrupt Unit can destroy a datapoint/data source and make it un-recoverable from the DB.

Caused by: com.serotonin.ShouldNeverHappenException: java.lang.IllegalArgumentException: java.text.ParseException: K? not recognized (in [K?] at index 1) at com.serotonin.util.SerializationHelper.readObjectInContext(SerializationHelper.java:93) at com.serotonin.m2m2.db.dao.DataPointDao$DataPointRowMapper.mapRow(DataPointDao.java:165) at com.serotonin.m2m2.db.dao.DataPointDao$DataPointRowMapper.mapRow(DataPointDao.java:160) at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93) at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60) at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:457) at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:468) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:478) at com.serotonin.db.DaoUtils.query(DaoUtils.java:304) at com.serotonin.m2m2.db.dao.DataPointDao.getDataPoints(DataPointDao.java:108) at com.serotonin.m2m2.web.mvc.controller.BaseDataSourceController.handleRequestInternal(BaseDataSourceController.java:187) at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154) at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) ... 35 more Caused by: java.lang.IllegalArgumentException: java.text.ParseException: K? not recognized (in [K?] at index 1) at com.serotonin.m2m2.util.UnitUtil.parseUcum(UnitUtil.java:80) at com.serotonin.m2m2.vo.DataPointVO.readObject(DataPointVO.java:1295) at

**Comment by terrypacker** [comment]
closing as done.
