### ISSUE TITLE
Error exporting Large Amounts of Point Values into XLSX Format

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#354]
Proper error checking should be done prior to export to ensure we don't fail after a long export is underway.

java.lang.IllegalArgumentException: Invalid row number (1048576) outside allowable range (0..1048575)
    at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:105)
    at com.serotonin.m2m2.rt.dataImage.PointValueEmporter.exportRow(PointValueEmporter.java:299)
    at com.serotonin.m2m2.web.servlet.ChartExportServlet$2.row(ChartExportServlet.java:147)
    at com.serotonin.m2m2.web.servlet.ChartExportServlet$2.row(ChartExportServlet.java:138)
    at com.infiniteautomation.nosql.MangoNoSqlPointValueDao$MappedRowPointValueQueryCallback.sample(MangoNoSqlPointValueDao.java:581)
    at com.infiniteautomation.nosql.MangoNoSqlPointValueDao$MappedRowPointValueQueryCallback.sample(MangoNoSqlPointValueDao.java:566)
    at org.tinytsdb.impl.TinyTSDBImpl$CallbackWrapper.sample(TinyTSDBImpl.java:364)
    at org.tinytsdb.impl.Shard.query(Shard.java:154)
    at org.tinytsdb.impl.Series.query(Series.java:146)
    at org.tinytsdb.impl.TinyTSDBImpl.query(TinyTSDBImpl.java:287)
    at org.tinytsdb.impl.TinyTSDBImpl.query(TinyTSDBImpl.java:269)
    at com.infiniteautomation.nosql.MangoNoSqlPointValueDao.getPointValuesBetween(MangoNoSqlPointValueDao.java:221)
    at com.serotonin.m2m2.web.servlet.ChartExportServlet.exportExcel(ChartExportServlet.java:161)
    at com.serotonin.m2m2.web.servlet.ChartExportServlet.doGet(ChartExportServlet.java:50)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:485)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
    at java.lang.Thread.run(Thread.java:745)

**Comment by terrypacker** [comment]
This is the same as #227

**Comment by terrypacker** [comment]
Capture this failure and perhaps indicate to the user that they should use CSV as Excel can't handle this much data.

**Comment by terrypacker** [comment]
Closing as tested as best we can.
