### ISSUE TITLE
Meta Data Points Startup Failures

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#363]
This is most likely due to the context point being inside of another Meta Data source that hasn't started yet.  Meta Data sources start last but we don't order them to start without failures and links to other Meta Points.

ERROR 2015-03-26 07:59:33,493 (com.serotonin.m2m2.meta.JavaScriptPointLocatorRT.createContext:64) -  
com.serotonin.m2m2.rt.script.DataPointStateException
	at com.serotonin.m2m2.rt.script.CompiledScriptExecutor.convertScriptContext(CompiledScriptExecutor.java:71)
	at com.serotonin.m2m2.meta.JavaScriptPointLocatorRT.createContext(JavaScriptPointLocatorRT.java:61)
	at com.serotonin.m2m2.meta.MetaPointLocatorRT.initialize(MetaPointLocatorRT.java:87)
	at com.serotonin.m2m2.meta.MetaDataSourceRT.addDataPoint(MetaDataSourceRT.java:44)
	at com.serotonin.m2m2.rt.RuntimeManager.startDataPoint(RuntimeManager.java:398)
	at com.serotonin.m2m2.rt.RuntimeManager.initializeDataSource(RuntimeManager.java:295)
	at com.serotonin.m2m2.rt.RuntimeManager.initialize(RuntimeManager.java:120)
	at com.serotonin.m2m2.Lifecycle.runtimeManagerInitialize(Lifecycle.java:627)
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:260)
	at com.serotonin.m2m2.Main.main(Main.java:104)
ERROR 2015-03-26 07:59:34,177 (com.serotonin.m2m2.meta.JavaScriptPointLocatorRT.createContext:64) -  
com.serotonin.m2m2.rt.script.DataPointStateException
	at com.serotonin.m2m2.rt.script.CompiledScriptExecutor.convertScriptContext(CompiledScriptExecutor.java:71)
	at com.serotonin.m2m2.meta.JavaScriptPointLocatorRT.createContext(JavaScriptPointLocatorRT.java:61)
	at com.serotonin.m2m2.meta.MetaPointLocatorRT.initialize(MetaPointLocatorRT.java:87)
	at com.serotonin.m2m2.meta.MetaDataSourceRT.addDataPoint(MetaDataSourceRT.java:44)
	at com.serotonin.m2m2.rt.RuntimeManager.startDataPoint(RuntimeManager.java:398)
	at com.serotonin.m2m2.rt.RuntimeManager.initializeDataSource(RuntimeManager.java:295)
	at com.serotonin.m2m2.rt.RuntimeManager.initialize(RuntimeManager.java:120)
	at com.serotonin.m2m2.Lifecycle.runtimeManagerInitialize(Lifecycle.java:627)
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:260)
	at com.serotonin.m2m2.Main.main(Main.java:104)

**Comment by terrypacker** [comment]
This has been fixed by creating the context every time the point is run until it is successfully created.  The point will still fail to run if the context can't be created but at least now it will re-try the next time the point is actioned to run its script.
