### ISSUE TITLE
NoSQL - Data Merge, High priority pool problem

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#646]
I attempted to perform a merge with 6000 threads in the high priority pool, and the exception i get back is:

FATAL 2016-02-12 12:32:36,464 (com.serotonin.timer.TimerThread.run:41) - TimerThread failed
java.lang.ClassCastException: com.serotonin.timer.OrderedThreadPoolExecutor$OrderedTask cannot be cast to com.serotonin.timer.OrderedTimerTaskWorker
        at com.serotonin.timer.OrderedRealTimeTimer.rejectedExecution(OrderedRealTimeTimer.java:55)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
        at com.serotonin.timer.OrderedThreadPoolExecutor.execute(OrderedThreadPoolExecutor.java:113)
        at com.serotonin.timer.OrderedTimerThread.executeTask(OrderedTimerThread.java:27)
        at com.serotonin.timer.TimerThread.mainLoop(TimerThread.java:127)
        at com.serotonin.timer.TimerThread.run(TimerThread.java:38)

But I still get many INFO messages thereafter about finishing certain data merge items.

**Comment by Puckfist** [comment]
This may have been caused by poor building on my part. I will retest and confirm.

**Comment by Puckfist** [comment]
Confirmed, my bad build caused it.
