### ISSUE TITLE
Apache POI - Upgrade Library

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#692]
If the temp directory or the folder 'poifiles' within it is deleted while Mango is running no Excel reports or Excel files can be created, a file not found exception will be thrown.  Upgraded to the latest dev version will fix this.

https://bz.apache.org/bugzilla/show_bug.cgi?id=57200

**Comment by terrypacker** [comment]
Until this bug is resolved it would ok to use a different java.io.tmpdir as passed into Mango.

**Comment by Puckfist** [comment]
The bug tracker referenced has someone commenting on 11-1-16 that they have resolved this.

**Comment by terrypacker** [comment]
Moving to 2.8.x so we can release a new module in the near future.

**Comment by terrypacker** [comment]
Closing as fixed, upgraded to 3.14

**Comment by Puckfist** [comment]
There is now a 3.17

**Comment by Puckfist** [comment]
Got this stack trace on trying to run a report for an unrelated reason,

ERROR 2018-04-09T12:38:34,821 [low-pool-4-thread-1] - getFileMagic() only operates on streams which support mark(int) 
java.io.IOException: getFileMagic() only operates on streams which support mark(int)
	at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:131) ~[poi-3.17.jar:3.17]
	at com.infiniteautomation.mango.excelreports.rt.ExcelReportWorkItem.execute(ExcelReportWorkItem.java:227) ~[?:?]
	at com.serotonin.m2m2.rt.maint.BackgroundProcessingImpl$WorkItemRunnable.run(BackgroundProcessingImpl.java:674) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
