### ISSUE TITLE
Meta Point - NPE on final cron instant

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#954]
If one sets a Meta point to a cron pattern that does not have any more times described by the pattern, such as "0 8 13 28 2 ? 2017" one will get a NullPointerException escaping to stderr like... 

Exception in thread "high-pool-2-thread-3" java.lang.NullPointerException
	at com.serotonin.m2m2.meta.MetaPointLocatorRT.calculateTimeout(MetaPointLocatorRT.java:229)
	at com.serotonin.m2m2.meta.MetaPointLocatorRT$ScheduledUpdateTimeout.run(MetaPointLocatorRT.java:216)
	at com.serotonin.timer.TimerTask.runTask(TimerTask.java:148)
	at com.serotonin.timer.OrderedTimerTaskWorker.run(OrderedTimerTaskWorker.java:29)
	at com.serotonin.timer.OrderedThreadPoolExecutor$OrderedTask.run(OrderedThreadPoolExecutor.java:278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Puckfist** [comment]
This likely affects anything running on a cron (but who knows how many people specify the year in their cron patterns....)

**Comment by Puckfist** [comment]
Our cron patterns should work fine until 2199, and then, speaking for myself, it's the next guy's problem. Closing as won't fix, there's already handling around this method to deal with the RTE if it occurs.
