### ISSUE TITLE
Upgrade16 failure on H2

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#966]
```
INFO  2017-03-30T10:04:45,149 (com.serotonin.m2m2.db.H2Proxy.initializeImpl:42) - Initializing H2 connection manager 
WARN  2017-03-30T10:04:47,660 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'core' from 13 to 14 
INFO  2017-03-30T10:04:47,661 (com.serotonin.m2m2.db.upgrade.DBUpgrade.createUpdateLogOutputStream:152) - Writing upgrade log to C:\Users\Jared\mango-main\ma-core-public\Core\logs\com.serotonin.m2m2.db.upgrade.Upgrade13.log 
WARN  2017-03-30T10:04:47,736 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'core' from 14 to 15 
INFO  2017-03-30T10:04:47,736 (com.serotonin.m2m2.db.upgrade.DBUpgrade.createUpdateLogOutputStream:152) - Writing upgrade log to C:\Users\Jared\mango-main\ma-core-public\Core\logs\com.serotonin.m2m2.db.upgrade.Upgrade14.log 
WARN  2017-03-30T10:04:47,755 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'core' from 15 to 16 
INFO  2017-03-30T10:04:47,755 (com.serotonin.m2m2.db.upgrade.DBUpgrade.createUpdateLogOutputStream:152) - Writing upgrade log to C:\Users\Jared\mango-main\ma-core-public\Core\logs\com.serotonin.m2m2.db.upgrade.Upgrade15.log 
WARN  2017-03-30T10:04:47,772 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'core' from 16 to 17 
INFO  2017-03-30T10:04:47,772 (com.serotonin.m2m2.db.upgrade.DBUpgrade.createUpdateLogOutputStream:152) - Writing upgrade log to C:\Users\Jared\mango-main\ma-core-public\Core\logs\com.serotonin.m2m2.db.upgrade.Upgrade16.log 
ERROR 2017-03-30T10:04:48,003 (com.serotonin.m2m2.Main.main:125) - Error during initialization 
com.serotonin.ShouldNeverHappenException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ UPDATE TABLE mailingLists SET receiveAlarmEmails=-3; ]; nested exception is org.h2.jdbc.JdbcSQLException: Table "TABLE" not found; SQL statement:
 UPDATE TABLE mailingLists SET receiveAlarmEmails=-3;  [42102-181]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:102) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:34) ~[classes/:?]
	at com.serotonin.m2m2.db.DatabaseProxy.initialize(DatabaseProxy.java:181) ~[classes/:?]
	at com.serotonin.m2m2.Lifecycle.databaseInitialize(Lifecycle.java:605) ~[classes/:?]
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:253) ~[classes/:?]
	at com.serotonin.m2m2.Main.main(Main.java:121) [classes/:?]
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ UPDATE TABLE mailingLists SET receiveAlarmEmails=-3; ]; nested exception is org.h2.jdbc.JdbcSQLException: Table "TABLE" not found; SQL statement:
 UPDATE TABLE mailingLists SET receiveAlarmEmails=-3;  [42102-181]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.serotonin.m2m2.db.H2Proxy.runScript(H2Proxy.java:149) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:129) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:143) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:134) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.Upgrade16.upgrade(Upgrade16.java:17) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:98) ~[classes/:?]
	... 5 more
Caused by: org.h2.jdbc.JdbcSQLException: Table "TABLE" not found; SQL statement:
 UPDATE TABLE mailingLists SET receiveAlarmEmails=-3;  [42102-181]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.readTableOrView(Parser.java:5227) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.readTableOrView(Parser.java:5204) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:759) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.parseUpdate(Parser.java:708) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.parsePrepared(Parser.java:455) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.parse(Parser.java:305) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.parse(Parser.java:277) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.command.Parser.prepareCommand(Parser.java:242) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.engine.Session.prepareLocal(Session.java:446) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.engine.Session.prepareCommand(Session.java:388) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:171) ~[h2-1.4.181.jar:1.4.181]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:159) ~[h2-1.4.181.jar:1.4.181]
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:435) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443) ~[spring-jdbc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.serotonin.m2m2.db.H2Proxy.runScript(H2Proxy.java:149) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:129) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:143) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:134) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.Upgrade16.upgrade(Upgrade16.java:17) ~[classes/:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:98) ~[classes/:?]
	... 5 more
```

**Comment by Puckfist** [comment]
whoops
