### ISSUE TITLE
NPE EmailWorkItem get description

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#999]
Email work item's get their fromAddress set in their execute method, but it is dereferenced in the description method anyway! Also why check if fromAddress == null... doesn't it always at that line?

**Comment by Puckfist** [comment]
Here's the trace that showed it to me:
ERROR 2017-05-05 09:34:53,548 (com.serotonin.m2m2.rt.maint.BackgroundProcessing$1.run:57) - Error in work item
java.lang.NullPointerException
        at com.serotonin.m2m2.rt.maint.work.EmailWorkItem.getDescription(EmailWorkItem.java:116)
        at com.serotonin.m2m2.rt.maint.BackgroundProcessing$1.toString(BackgroundProcessing.java:63)
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2045)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at com.serotonin.m2m2.rt.maint.BackgroundProcessing.addWorkItem(BackgroundProcessing.java:82)
        at com.serotonin.m2m2.rt.maint.work.EmailWorkItem.queueEmail(EmailWorkItem.java:59)
        at com.infiniteautomation.mango.excelreports.rt.ExcelReportWorkItem.emailReport(ExcelReportWorkItem.java:608)
        at com.infiniteautomation.mango.excelreports.rt.ExcelReportWorkItem.execute(ExcelReportWorkItem.java:552)
        at com.serotonin.m2m2.rt.maint.BackgroundProcessing$1.run(BackgroundProcessing.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
